menu:
- {name: 'home', url: ''}
- {name: 'research', url: '/research'}
- {name: 'academic presentations', url: '/academicpresentations'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'mdi:github', link: 'https://github.com/AriadnaVillavicencioGamarra'}
- {icon: 'mdi:linkedin', link: 'https://www.linkedin.com/in/ariadnavillaicenciogamarra/'}
- {icon: 'mdi:email', link: 'mailto:villavia@whitman.edu'}

